# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3
# test:
#   <<: *default
#   database: db_development

# production:
#   <<: *default
#   database: db_development




default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: synata_development

test:
  <<: *default
  database: synata_test

production:
  <<: *default
  database: synata_production
  username: ruby-rails-synata
  password: <%= ENV['RUBY-RAILS-SAMPLE_DATABASE_PASSWORD'] %>